language: julia
os:
  - linux
  # - osx
julia:
  - 0.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e Pkg.add("Reel"); Pkg.checkout("Reel"); Pkg.clone(pwd()); Pkg.test("AutoViz"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("AutoViz")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
